services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: unless-stopped
    # Simpler healthcheck
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/offer-contract-system
      - PORT=3000
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    # Simple command to seed and start
    command: >
      sh -c "
        echo 'Seeding the database...' &&
        node scripts/seed-database.js &&
        echo 'Starting the application...' &&
        npm run start
      "

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local